// server/routes/mcq.js
import express from 'express';
import { v4 as uuidv4 } from 'uuid';
import { query, getOne } from '../db.js';
import { authenticate } from '../middleware/auth.js';
import { generateMCQQuestions, evaluateAnswers } from '../services/gemini.js';

const router = express.Router();

// POST /api/mcq/session - Create new MCQ session (Gemini only - NO FALLBACK)
router.post('/session', authenticate, async (req, res) => {
  try {
    const { jobRole, topic, questionCount } = req.body;
    
    if (!jobRole) {
      return res.status(400).json({ error: 'jobRole is required' });
    }
    
    const sessionId = uuidv4();
    
    console.log('📝 Creating MCQ session:', { jobRole, topic, questionCount, userId: req.user.id });
    
    // Generate questions from Gemini ONLY
    let questions;
    try {
      questions = await generateMCQQuestions(jobRole, topic, questionCount);
      
      if (!questions || questions.length === 0) {
        throw new Error('No questions generated by Gemini');
      }
      
      console.log(`Gemini generated ${questions.length} questions`);
      
    } catch (geminiError) {
      console.error('Gemini API error:', geminiError.message);
      return res.status(503).json({ 
        error: 'Unable to generate questions from AI service',
        details: geminiError.message,
        suggestion: 'Please check your Gemini API key or try again later.'
      });
    }
    
    // Save session to database
    await query(
      `INSERT INTO mcq_sessions (id, user_id, job_role, topic, total_questions, status, created_at)
       VALUES (?, ?, ?, ?, ?, 'in_progress', NOW())`,
      [sessionId, req.user.id, jobRole, topic, questions.length]
    );
    
    // Save questions to database
    for (let i = 0; i < questions.length; i++) {
      const q = questions[i];
      const questionId = uuidv4();
      await query(
        `INSERT INTO mcq_questions (id, session_id, question_number, question, options, correct_answer, explanation, difficulty, topic)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [questionId, sessionId, i + 1, q.question, JSON.stringify(q.options), q.correct, q.explanation, q.difficulty || 'medium', topic]
      );
    }
    
    // Return questions WITHOUT exposing correct answers
    const questionsForClient = questions.map((q, index) => ({
      id: `q_${index + 1}`,
      questionNumber: index + 1,
      question: q.question,
      options: q.options
    }));
    
    console.log('Session created successfully:', sessionId);
    
    res.status(201).json({ 
      sessionId, 
      questions: questionsForClient,
      totalQuestions: questions.length,
      source: 'Gemini AI'
    });
    
  } catch (error) {
    console.error('Error creating MCQ session:', error);
    res.status(500).json({ error: 'Failed to create MCQ session: ' + error.message });
  }
});

// GET /api/mcq/session/:sessionId - Get session details (INCLUDES USER ANSWERS)
router.get('/session/:sessionId', authenticate, async (req, res) => {
  try {
    const { sessionId } = req.params;
    
    console.log('Fetching session:', sessionId, 'for user:', req.user.id);
    
    if (!sessionId) {
      return res.status(400).json({ error: 'Session ID is required' });
    }
    
    // Get session
    const session = await getOne(
      'SELECT * FROM mcq_sessions WHERE id = ? AND user_id = ?',
      [sessionId, req.user.id]
    );
    
    if (!session) {
      console.log('Session not found:', sessionId);
      return res.status(404).json({ error: 'Session not found' });
    }
    
    // Get questions WITH user answers (for results page)
    const questions = await query(
      `SELECT id, question_number, question, options, correct_answer, user_answer, explanation, is_correct, score 
       FROM mcq_questions 
       WHERE session_id = ? 
       ORDER BY question_number`,
      [sessionId]
    );
    
    if (!questions || questions.length === 0) {
      console.log('No questions found for session:', sessionId);
      return res.status(404).json({ error: 'No questions found for this session' });
    }
    
    // Parse options JSON for each question
    const parsedQuestions = questions.map(q => {
      let options = [];
      try {
        options = typeof q.options === 'string' ? JSON.parse(q.options) : q.options;
      } catch (e) {
        console.error('Error parsing options:', e);
        options = ['Option A', 'Option B', 'Option C', 'Option D'];
      }
      return {
        id: q.id,
        questionNumber: q.question_number,
        question: q.question,
        options: options,
        correct_answer: q.correct_answer,
        user_answer: q.user_answer,
        explanation: q.explanation,
        is_correct: q.is_correct,
        score: q.score
      };
    });
    
    console.log(`✅ Returning ${parsedQuestions.length} questions with answers`);
    
    res.json({ 
      session, 
      questions: parsedQuestions 
    });
    
  } catch (error) {
    console.error('Error fetching MCQ session:', error);
    res.status(500).json({ error: 'Failed to fetch session: ' + error.message });
  }
});

// POST /api/mcq/submit/:sessionId - Submit answers
router.post('/submit/:sessionId', authenticate, async (req, res) => {
  try {
    const { sessionId } = req.params;
    const { answers } = req.body;
    
    console.log('Submitting answers for session:', sessionId);
    
    if (!answers || !Array.isArray(answers)) {
      return res.status(400).json({ error: 'Answers array is required' });
    }
    
    // Get session
    const session = await getOne(
      'SELECT * FROM mcq_sessions WHERE id = ? AND user_id = ?',
      [sessionId, req.user.id]
    );
    
    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }
    
    if (session.status === 'completed') {
      return res.status(400).json({ error: 'Session already completed' });
    }
    
    // Get questions
    const questions = await query(
      'SELECT * FROM mcq_questions WHERE session_id = ? ORDER BY question_number',
      [sessionId]
    );
    
    if (questions.length === 0) {
      return res.status(404).json({ error: 'No questions found' });
    }
    
    if (answers.length !== questions.length) {
      return res.status(400).json({ 
        error: `Expected ${questions.length} answers, got ${answers.length}`
      });
    }
    
    // Prepare for evaluation
    const questionData = questions.map(q => {
      let options = [];
      try {
        options = typeof q.options === 'string' ? JSON.parse(q.options) : q.options;
      } catch (e) {
        options = ['Option A', 'Option B', 'Option C', 'Option D'];
      }
      return {
        question: q.question,
        options: options,
        correct: q.correct_answer,
        explanation: q.explanation
      };
    });
    
    // Evaluate answers
    const evaluation = evaluateAnswers(questionData, answers);
    
    // Save answers
    let correctCount = 0;
    for (let i = 0; i < questions.length; i++) {
      const isCorrect = evaluation.results[i].isCorrect;
      if (isCorrect) correctCount++;
      
      await query(
        `UPDATE mcq_questions 
         SET user_answer = ?, is_correct = ?, score = ?, answered_at = NOW()
         WHERE id = ?`,
        [answers[i], isCorrect, isCorrect ? 1 : 0, questions[i].id]
      );
    }
    
    // Update session
    await query(
      `UPDATE mcq_sessions 
       SET status = 'completed', score = ?, correct_count = ?, completed_at = NOW()
       WHERE id = ?`,
      [evaluation.score, correctCount, sessionId]
    );
    
    console.log(`Session completed. Score: ${evaluation.score}%`);
    
    res.json({
      sessionId,
      score: evaluation.score,
      correctCount: correctCount,
      totalQuestions: evaluation.totalQuestions,
      results: evaluation.results,
      message: evaluation.message
    });
    
  } catch (error) {
    console.error('Error submitting answers:', error);
    res.status(500).json({ error: 'Failed to submit answers: ' + error.message });
  }
});

// GET /api/mcq/sessions - Get all user sessions
router.get('/sessions', authenticate, async (req, res) => {
  try {
    const sessions = await query(
      `SELECT id, job_role, topic, total_questions, correct_count, score, status, created_at, completed_at
       FROM mcq_sessions 
       WHERE user_id = ? 
       ORDER BY created_at DESC 
       LIMIT 20`,
      [req.user.id]
    );
    
    res.json({ sessions: sessions || [] });
  } catch (error) {
    console.error('Error fetching sessions:', error);
    res.status(500).json({ error: 'Failed to fetch sessions' });
  }
});

// DELETE /api/mcq/session/:sessionId - Delete session
router.delete('/session/:sessionId', authenticate, async (req, res) => {
  try {
    const { sessionId } = req.params;
    
    const session = await getOne(
      'SELECT id FROM mcq_sessions WHERE id = ? AND user_id = ?',
      [sessionId, req.user.id]
    );
    
    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }
    
    await query('DELETE FROM mcq_sessions WHERE id = ?', [sessionId]);
    
    res.json({ message: 'Session deleted successfully' });
  } catch (error) {
    console.error('Error deleting session:', error);
    res.status(500).json({ error: 'Failed to delete session' });
  }
});

export default router;